# Generated by Django 5.2.5 on 2025-08-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('long_description', models.TextField(blank=True, help_text='Подробное описание проекта (поддержка Markdown)', null=True, verbose_name='Полное описание')),
                ('tech', models.JSONField(help_text="Список технологий, например: ['React', 'Redux']", verbose_name='Технологии')),
                ('category', models.CharField(choices=[('All', 'All'), ('React', 'React'), ('Vue', 'Vue'), ('Angular', 'Angular'), ('Node.js', 'Node.js'), ('TypeScript', 'TypeScript'), ('Fullstack', 'Fullstack'), ('Mobile', 'Mobile')], max_length=20, verbose_name='Категория')),
                ('status', models.CharField(choices=[('in-progress', 'В работе'), ('frozen', 'Заморожен'), ('completed', 'Завершен'), ('draft', 'Черновик'), ('archived', 'В архиве')], max_length=20, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, help_text='Превью проекта (главная картинка в карточке)', null=True, upload_to='projects/%Y/%m/', verbose_name='Основное изображение')),
                ('source_url', models.URLField(blank=True, help_text='GitHub/GitLab репозиторий', null=True, verbose_name='Ссылка на исходный код')),
                ('demo_url', models.URLField(blank=True, help_text='Прямая ссылка на запущенный проект (например, Vercel)', null=True, verbose_name='Ссылка на демо')),
                ('client', models.CharField(blank=True, help_text='Для кого был сделан проект', max_length=100, null=True, verbose_name='Клиент / Цель')),
                ('project_type', models.CharField(blank=True, choices=[('personal', 'Личный'), ('freelance', 'Фриланс'), ('team', 'Командный'), ('work', 'Рабочий')], max_length=20, null=True, verbose_name='Тип проекта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('features', models.JSONField(blank=True, help_text='["PWA", "Аутентификация", "Оффлайн-режим"]', null=True, verbose_name='Ключевые особенности')),
                ('apis_used', models.JSONField(blank=True, help_text='["OpenWeather API", "Stripe"]', null=True, verbose_name='Используемые API')),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, help_text='Оценка сложности проекта', null=True, verbose_name='Сложность (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/%Y/%m/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись (alt)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше — тем выше в галерее', verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Галерея проектов',
                'ordering': ['order'],
            },
        ),
    ]
